#Part A – Data Extraction

#Task 1
Read the Population dataset from the CSV file.

Hint:

● Use the pandas library.


● Display the first five rows.


● Check the shape and data types.

In [2]:
import pandas as pd

In [3]:
population = pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [4]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [5]:
population .shape

(25, 2)

In [6]:
population.dtypes

country       object
population     int64
dtype: object

#Task 2
Read the GDP dataset from the Excel file.


Hint:


● Use the appropriate pandas function.

● Display column names and data types.

In [7]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [8]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [9]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

#Task 3


Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame.

In [10]:
internet_users= pd.read_json('/content/internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [11]:
internet_users= pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [12]:
internet_users  = pd.DataFrame(internet_users)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Task 4

Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [63]:
data_set = pd.read_xml('/content/literacy_rate.xml')
data_set

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [64]:
data_set = pd.DataFrame(data_set)
data_set

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Part B – Data Understanding

Task 5

Explore each dataset.
Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [26]:
population = pd.read_csv('/content/population.csv')
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [15]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [16]:
population.columns

Index(['country', 'population'], dtype='object')

In [17]:
population.dtypes

country       object
population     int64
dtype: object

In [18]:
population.count()

country       25
population    25
dtype: int64

In [19]:
population.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [20]:
population.duplicated().sum()

np.int64(0)

In [22]:
len(population)

25

In [25]:
population.isnull().sum()

country       0
population    0
dtype: int64

In [27]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [28]:
gdp.head()

         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

In [30]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [31]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [32]:
gdp.count()

Country    25
GDP        25
dtype: int64

In [33]:
gdp.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [34]:
gdp.duplicated().sum()

np.int64(0)

In [35]:
len(gdp)

25

In [36]:
gdp.isnull().sum()

Country    0
GDP        0
dtype: int64

In [40]:
internet_users= pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [41]:
internet_users.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

In [42]:
internet_users.columns

Index(['country', 'internet_users'], dtype='object')

In [43]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [44]:
internet_users.count()

country           25
internet_users    25
dtype: int64

In [45]:
internet_users.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [46]:
internet_users.duplicated().sum()

np.int64(0)

In [47]:
len(internet_users)

25

In [48]:
internet_users.isnull().sum()

country           0
internet_users    0
dtype: int64

In [49]:
data_set = pd.read_xml('/content/literacy_rate.xml')
data_set

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [50]:
data_set.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [51]:
data_set.columns

Index(['name', 'literacy_rate'], dtype='object')

In [52]:
data_set.dtypes

name              object
literacy_rate    float64
dtype: object

In [53]:
data_set.count()

name             25
literacy_rate    25
dtype: int64

In [54]:
data_set.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool

In [55]:
data_set.duplicated().sum()

np.int64(0)

In [56]:
len(data_set)

25

In [57]:
data_set.isnull().sum()

name             0
literacy_rate    0
dtype: int64

#Part C – Data Transformation


Task 6

Rename columns wherever necessary so that all datasets have a common column
name for merging.


Hint:
● Example: Country → country

In [128]:
data_set.rename(columns ={'Country': 'country'} ,inplace = True)
data_set

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [130]:
internet_users.rename(columns ={'Country': 'country'} ,inplace = True)
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [129]:
gdp.rename(columns ={'Country': 'country'} ,inplace = True)
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [131]:
population.rename(columns ={'Country': 'country'} ,inplace = True)
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

#task 7


Convert the required columns into appropriate numeric data types.

In [85]:
population["population"] = pd.to_numeric(population["population"])
population.dtypes

country       object
population     int64
dtype: object

In [77]:
internet_users["internet_users"] = pd.to_numeric(internet_users["internet_users"])
internet_users.dtypes

country           object
internet_users     int64
dtype: object

#Task 8

Merge all four datasets into one DataFrame.

Hint:

● Use the common column (country)

● Choose an appropriate join method.

In [135]:
merged_df = population.merge(internet_users, on="country", how="inner")\
.merge(gdp, on="country", how="inner")\
.merge(data_set, on="country", how="inner")

In [137]:
merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%)
0,United States,331002651,312000000,30500000,99.0,0.94
1,China,1411778724,1080000000,19230000,97.2,0.76
2,India,1380004385,850000000,4187000,77.7,0.62
3,Japan,125836021,118000000,4180000,99.0,0.94
4,Germany,83240525,79000000,4744000,99.0,0.95
5,United Kingdom,67886011,66000000,3839000,99.0,0.97
6,France,65273511,62000000,3211000,99.0,0.95
7,Italy,60461826,56000000,2420000,99.0,0.93
8,Canada,38005238,36000000,2250000,99.0,0.95
9,Australia,25687041,24000000,1880000,99.0,0.93
10,Brazil,212559417,181000000,2330000,93.2,0.85
11,Russia,145934462,125000000,2200000,99.7,0.86
12,South Korea,51780579,50000000,1800000,98.8,0.97
13,Spain,46754778,44000000,1710000,98.6,0.94
14,Mexico,128932753,102000000,1810000,95.4,0.79
15,Indonesia,273523615,212000000,1500000,96.0,0.78
16,Saudi Arabia,34813871,34000000,1100000,97.3,0.98
17,Turkey,84339067,69000000,1350000,96.7,0.82
18,South Africa,59308690,43000000,410000,95.0,0.73
19,Argentina,45195774,41000000,640000,99.1,0.91
20,Netherlands,17441139,17000000,1150000,99.0,0.97
21,Switzerland,8654622,8500000,940000,99.0,0.98
22,Sweden,10353442,10100000,650000,99.0,0.98
23,Norway,5421241,5300000,580000,100.0,0.98
24,Singapore,5850342,5600000,530000,97.5,0.96

#Task 9


Create the following calculated columns:

1. Internet Penetration (%)

2. GDP Per Capita

Hint:

Round the calculated values to two decimal places.

In [136]:
merged_df['internet_penetration (%) '] =(
    merged_df['internet_users'] / merged_df['population']
 ).round(2)

merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%)
0,United States,331002651,312000000,30500000,99.0,0.94
1,China,1411778724,1080000000,19230000,97.2,0.76
2,India,1380004385,850000000,4187000,77.7,0.62
3,Japan,125836021,118000000,4180000,99.0,0.94
4,Germany,83240525,79000000,4744000,99.0,0.95
5,United Kingdom,67886011,66000000,3839000,99.0,0.97
6,France,65273511,62000000,3211000,99.0,0.95
7,Italy,60461826,56000000,2420000,99.0,0.93
8,Canada,38005238,36000000,2250000,99.0,0.95
9,Australia,25687041,24000000,1880000,99.0,0.93
10,Brazil,212559417,181000000,2330000,93.2,0.85
11,Russia,145934462,125000000,2200000,99.7,0.86
12,South Korea,51780579,50000000,1800000,98.8,0.97
13,Spain,46754778,44000000,1710000,98.6,0.94
14,Mexico,128932753,102000000,1810000,95.4,0.79
15,Indonesia,273523615,212000000,1500000,96.0,0.78
16,Saudi Arabia,34813871,34000000,1100000,97.3,0.98
17,Turkey,84339067,69000000,1350000,96.7,0.82
18,South Africa,59308690,43000000,410000,95.0,0.73
19,Argentina,45195774,41000000,640000,99.1,0.91
20,Netherlands,17441139,17000000,1150000,99.0,0.97
21,Switzerland,8654622,8500000,940000,99.0,0.98
22,Sweden,10353442,10100000,650000,99.0,0.98
23,Norway,5421241,5300000,580000,100.0,0.98
24,Singapore,5850342,5600000,530000,97.5,0.96

In [102]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [111]:
merged_df["internet_penetration (%)"] = (
    merged_df["internet_users"] / merged_df["population"] * 100
).round(2)

In [141]:
merged_df["gdp_Per_Capita"] = (
    merged_df["GDP"]  / merged_df["population"]
).round(2)

In [143]:
merged_df

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_Per_Capita
0,United States,331002651,312000000,30500000,99.0,0.94,0.09
1,China,1411778724,1080000000,19230000,97.2,0.76,0.01
2,India,1380004385,850000000,4187000,77.7,0.62,0.00
3,Japan,125836021,118000000,4180000,99.0,0.94,0.03
4,Germany,83240525,79000000,4744000,99.0,0.95,0.06
5,United Kingdom,67886011,66000000,3839000,99.0,0.97,0.06
6,France,65273511,62000000,3211000,99.0,0.95,0.05
7,Italy,60461826,56000000,2420000,99.0,0.93,0.04
8,Canada,38005238,36000000,2250000,99.0,0.95,0.06
9,Australia,25687041,24000000,1880000,99.0,0.93,0.07
10,Brazil,212559417,181000000,2330000,93.2,0.85,0.01
11,Russia,145934462,125000000,2200000,99.7,0.86,0.02
12,South Korea,51780579,50000000,1800000,98.8,0.97,0.03
13,Spain,46754778,44000000,1710000,98.6,0.94,0.04
14,Mexico,128932753,102000000,1810000,95.4,0.79,0.01
15,Indonesia,273523615,212000000,1500000,96.0,0.78,0.01
16,Saudi Arabia,34813871,34000000,1100000,97.3,0.98,0.03
17,Turkey,84339067,69000000,1350000,96.7,0.82,0.02
18,South Africa,59308690,43000000,410000,95.0,0.73,0.01
19,Argentina,45195774,41000000,640000,99.1,0.91,0.01
20,Netherlands,17441139,17000000,1150000,99.0,0.97,0.07
21,Switzerland,8654622,8500000,940000,99.0,0.98,0.11
22,Sweden,10353442,10100000,650000,99.0,0.98,0.06
23,Norway,5421241,5300000,580000,100.0,0.98,0.11
24,Singapore,5850342,5600000,530000,97.5,0.96,0.09

#Part D – Load Data

Task 10

Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’


Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas

In [106]:
import sqlite3

In [241]:
conn = sqlite3.connect("conutry_statistics.db")
merged_df.to_sql("country_statistics",conn,
                 if_exists="replace",
                 index=False
                 )
conn.close()

In [108]:
conn = sqlite3.connect("conutry_statistics.db")

df = pd.read_sql("select * from  country_statistics",conn)

conn.close()

df

,country,population,internet_users,literacy_rate_x,literacy_rate_y,internet_penetration (%)
0,United States,331002651,312000000,99.0,99.0,0.94
1,China,1411778724,1080000000,97.2,97.2,0.76
2,India,1380004385,850000000,77.7,77.7,0.62
3,Japan,125836021,118000000,99.0,99.0,0.94
4,Germany,83240525,79000000,99.0,99.0,0.95
5,United Kingdom,67886011,66000000,99.0,99.0,0.97
6,France,65273511,62000000,99.0,99.0,0.95
7,Italy,60461826,56000000,99.0,99.0,0.93
8,Canada,38005238,36000000,99.0,99.0,0.95
9,Australia,25687041,24000000,99.0,99.0,0.93
10,Brazil,212559417,181000000,93.2,93.2,0.85
11,Russia,145934462,125000000,99.7,99.7,0.86
12,South Korea,51780579,50000000,98.8,98.8,0.97
13,Spain,46754778,44000000,98.6,98.6,0.94
14,Mexico,128932753,102000000,95.4,95.4,0.79
15,Indonesia,273523615,212000000,96.0,96.0,0.78
16,Saudi Arabia,34813871,34000000,97.3,97.3,0.98
17,Turkey,84339067,69000000,96.7,96.7,0.82
18,South Africa,59308690,43000000,95.0,95.0,0.73
19,Argentina,45195774,41000000,99.1,99.1,0.91
20,Netherlands,17441139,17000000,99.0,99.0,0.97
21,Switzerland,8654622,8500000,99.0,99.0,0.98
22,Sweden,10353442,10100000,99.0,99.0,0.98
23,Norway,5421241,5300000,100.0,100.0,0.98
24,Singapore,5850342,5600000,97.5,97.5,0.96

#Task 11

Verify that the data has been loaded successfully.


Hint:


Retrieve the first five records from the SQLite table.

In [109]:
df.head()

,country,population,internet_users,literacy_rate_x,literacy_rate_y,internet_penetration (%)
0,United States,331002651,312000000,99.0,99.0,0.94
1,China,1411778724,1080000000,97.2,97.2,0.76
2,India,1380004385,850000000,77.7,77.7,0.62
3,Japan,125836021,118000000,99.0,99.0,0.94
4,Germany,83240525,79000000,99.0,99.0,0.95

#Part E – Data Analysis Using Pandas


Answer the following questions using pandas.


1 List the Top 5 countries by GDP.


2 List the Top 5 countries by population.


3 Calculate the average literacy rate.


4 List all countries having a literacy rate greater than 90%.


5 List all countries having an internet penetration greater than 70%.


6 List the Top 5 countries by GDP per capita.


7 Calculate the total population represented in the dataset.


8 Calculate the average internet penetration across all countries.


9 Identify the country having the highest number of internet users.


10 Find the correlation between Literacy Rate and Internet Penetration.

Hint:


Use the appropriate pandas statistical function.

In [144]:
# 1. List the Top 5 countries by GDP.
gdp.head()

         country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

In [150]:
gdp = gdp.sort_values(by='GDP' , ascending=False)
gdp.head(5)

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [151]:
#2. List the Top 5 countries by population
population = population.sort_values(by='population' , ascending=False)
population.head(5)

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [152]:
 #3 Calculate the average literacy rate

data_set.groupby('country').mean()

                literacy_rate
country
Argentina                99.1
Australia                99.0
Brazil                   93.2
Canada                   99.0
China                    97.2
France                   99.0
Germany                  99.0
India                    77.7
Indonesia                96.0
Italy                    99.0
Japan                    99.0
Mexico                   95.4
Netherlands              99.0
Norway                  100.0
Russia                   99.7
Saudi Arabia             97.3
Singapore                97.5
South Africa             95.0
South Korea              98.8
Spain                    98.6
Sweden                   99.0
Switzerland              99.0
Turkey                   96.7
United Kingdom           99.0
United States            99.0

In [153]:
# 4 List all countries having a literacy rate greater than 90%
data_set[data_set['literacy_rate']>90]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [163]:
# 5 List all countries having an internet penetration greater than 70%

merged_df[merged_df[ 'internet_penetration (%) ' ] > 70]

Empty DataFrame
Columns: [country, population, internet_users, GDP, literacy_rate, internet_penetration (%) , gdp_Per_Capita]
Index: []

In [200]:
#6 List the Top 5 countries by GDP per capita
merged_df = merged_df.sort_values(by='gdp_Per_Capita', ascending = False)
merged_df.head(5)

,country,population,internet_users,GDP,literacy_rate,internet_penetration (%),gdp_Per_Capita
21,Switzerland,8654622,8500000,940000,99.0,0.98,0.11
23,Norway,5421241,5300000,580000,100.0,0.98,0.11
24,Singapore,5850342,5600000,530000,97.5,0.96,0.09
0,United States,331002651,312000000,30500000,99.0,0.94,0.09
9,Australia,25687041,24000000,1880000,99.0,0.93,0.07

In [201]:
#7 Calculate the total population represented in the dataset.
merged_df['population'].sum()

np.int64(4720039725)

In [202]:
#8 Calculate the average internet penetration across all countries
merged_df['internet_penetration (%) '].mean()

np.float64(0.8976000000000001)

In [204]:
#9 Identify the country having the highest number of internet users
merged_df.loc[merged_df['internet_users'].idxmax()][['country','internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

In [205]:
#10 Find the correlation between Literacy Rate and Internet Penetration
merged_df['literacy_rate'].corr(merged_df['internet_penetration (%) '])

np.float64(0.7706030781906815)

#Part F – Data Analysis Using SQL


Answer the following questions using SQLite queries.

In [247]:
#11 Display the Top 5 countries by GDP.
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5"
top5_gdp = pd.read_sql_query(q, conn)
conn.close()
print(top5_gdp)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [249]:
#12 Find the average literacy rate
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT AVG(literacy_rate) FROM country_statistics"
avg_literacy_rate = pd.read_sql_query(q, conn)
conn.close()
print(avg_literacy_rate)

   AVG(literacy_rate)
0              97.248

In [261]:
#13 Display all countries having literacy rate above 90%
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT country , literacy_rate  FROM country_statistics WHERE literacy_rate > 90 ORDER BY literacy_rate DESC"
df_filtered = pd.read_sql_query(q, conn)
conn.close()
print(df_filtered)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3      Switzerland           99.0
4    United States           99.0
5        Australia           99.0
6      Netherlands           99.0
7          Germany           99.0
8           Canada           99.0
9   United Kingdom           99.0
10          Sweden           99.0
11          France           99.0
12           Italy           99.0
13           Japan           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [251]:
# 14 Find the Top 5 countries with the highest internet penetration.
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT country, \"internet_penetration (%)\" FROM country_statistics ORDER BY \"internet_penetration (%)\" DESC LIMIT 5"
top5_internet_penetration = pd.read_sql_query(q, conn)
conn.close()
print(top5_internet_penetration)

         country "internet_penetration (%)"
0    Switzerland   internet_penetration (%)
1         Norway   internet_penetration (%)
2      Singapore   internet_penetration (%)
3  United States   internet_penetration (%)
4      Australia   internet_penetration (%)

In [252]:
#15 Calculate the total population.
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT SUM(population) FROM country_statistics"
total_population = pd.read_sql_query(q, conn)
conn.close()
print(total_population)

   SUM(population)
0       4720039725

In [253]:
#16 Find the country with the highest GDP per capita.
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = 'SELECT country , gdp_Per_Capita FROM country_statistics  ORDER BY gdp_Per_Capita  DESC LIMIT 1'
df_filtered_gdp_Per_Capita = pd.read_sql_query(q,conn)
conn.close()
print(df_filtered_gdp_Per_Capita)
print("\n")

       country  gdp_Per_Capita
0  Switzerland            0.11

In [254]:
#17 Export the final merged dataset as a CSV file
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
final_df = pd.read_sql_query("SELECT * FROM country_statistics", conn)
conn.close()
final_df.to_csv('country_statics.csv', index = False)
print("Dataset exported to 'country_statistics.csv',")
print("\n")

Dataset exported to 'country_statistics.csv',

In [255]:
#18 Sort the dataset in descending order of GDP per Capita and display the Top
import sqlite3
conn = sqlite3.connect('conutry_statistics.db')
q = "SELECT country, gdp_Per_Capita FROM country_statistics ORDER BY gdp_Per_Capita DESC LIMIT 10"
df_top10_gdp_Per_capita = pd.read_sql_query(q, conn)
conn.close()
print(df_top10_gdp_Per_capita)
print("\n")

          country  gdp_Per_Capita
0     Switzerland            0.11
1          Norway            0.11
2       Singapore            0.09
3   United States            0.09
4       Australia            0.07
5     Netherlands            0.07
6         Germany            0.06
7          Canada            0.06
8  United Kingdom            0.06
9          Sweden            0.06